var movies = [{
    "Title": "Patton Oswalt: Annihilation",
    "fulltitle": "Patton Oswalt: Annihilation (2017)",
    "movie_year": 2017,
    "Categories": "Uncategorized",
    "summary": "Patton Oswald, despite a personal tragedy, produces his best standup yet. Focusing on the tribulations of the Trump era and life after the loss of a loved one, Patton Oswald continues his journey to contribute joy to the world.",
    "ImageURL": "https://m.media-amazon.com/images/M/MV5BNDgwZGVlMDItNzJhZi00NGE3LThkOWYtODE5ODgzNTlhMDA0XkEyXkFqcGdeQXVyMjc0MzU3MzE@._V1_.jpg",
    "imdb_id": "tt7026230",
    "imdb_rating": 7.4,
    "runtime": 66,
    "language": "English",
    "ytid": "4hZi5QaMBFc"
},
{
    "Title": "New York Doll",
    "fulltitle": "New York Doll (2005)",
    "movie_year": 2005,
    "Categories": "Documentary|Music",
    "summary": "A recovering alcoholic and recently converted Mormon, Arthur \"Killer\" Kane, of the rock band The New York Dolls, is given a chance at reuniting with his band after 30 years.",
    "ImageURL": "https://npr.brightspotcdn.com/dims4/default/2e09700/2147483647/strip/true/crop/498x311+0+0/resize/880x550!/quality/90/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Flegacy%2Fsites%2Fradiowest%2Ffiles%2F201906%2Fnew_york_doll_cropped_wikimedia_commons.png",
    "imdb_id": "tt0436629",
    "imdb_rating": 7.9,
    "runtime": 75,
    "language": "English",
    "ytid": "jwD04NsnLLg"
},
{
    "Title": "Mickey's Magical Christmas: Snowed in at the House of Mouse",
    "fulltitle": "Mickey's Magical Christmas: Snowed in at the House of Mouse (2001)",
    "movie_year": 2001,
    "Categories": "Adventure|Animation|Comedy|Family|Fantasy",
    "summary": "After everyone is snowed in at the House of Mouse, Mickey suggests they throw their own Christmas party. Everyone is happy, except for Donald who just isn't in to the Christmas spirit. So Mickey shows a series of cartoons that show just what Christmas is all about. It features a star studded cast of Disney characters from everyone's favorite animated Disney movies.",
    "ImageURL": "https://i.ytimg.com/vi/UlxH3aJOZvs/maxresdefault.jpg",
    "imdb_id": "tt0300195",
    "imdb_rating": 6.8,
    "runtime": 65,
    "language": "English",
    "ytid": "uCKwHHftrU4"
},
{
    "Title": "Mickey's House of Villains",
    "fulltitle": "Mickey's House of Villains (2001)",
    "movie_year": 2001,
    "Categories": "Animation|Comedy|Family|Fantasy|Horror",
    "summary": "The villains from the popular animated Disney films are gathered at the House of Mouse with plans to take over. Soon, the villains take over the house and kick out Mickey, Donald and Goofy. It's all up to Mickey and his friends to overthrow evil and return the House of Mouse to normal--or as close to normal as it get's.",
    "ImageURL": "https://assets.mubicdn.net/images/film/53901/image-w1280.jpg?1602385219",
    "imdb_id": "tt0329374",
    "imdb_rating": 6.6,
    "runtime": 0,
    "language": "English",
    "ytid": "JA03ciYt-Ek"
},
{
    "Title": "And Then I Go",
    "fulltitle": "And Then I Go (2017)",
    "movie_year": 2017,
    "Categories": "Drama",
    "summary": "In the cruel world of junior high, Edwin suffers in a state of anxiety and alienation alongside his only friend, Flake. Misunderstood by their families and demoralized at school daily, their fury simmers quietly until an idea for vengeance offers them a terrifying release. Based on the acclaimed novel \"Project X\" by Jim Shepard, this unflinching look at adolescence explores how the powerful bonds of childhood friendship and search for belonging can become a matter of life or death.",
    "ImageURL": "https://lh3.googleusercontent.com/9QEjkbHd5-UEzs7IOWN0rwKzBzlW6Q8TUu8I0M7B7hwpAcywKQTB4gRZS5BHwojKTKdeNrBN45o",
    "imdb_id": "tt2018111",
    "imdb_rating": 7.6,
    "runtime": 99,
    "language": "English",
    "ytid": "8CdIiD6-iF0"
},
{
    "Title": "An Extremely Goofy Movie",
    "fulltitle": "An Extremely Goofy Movie (2000)",
    "movie_year": 2000,
    "Categories": "Animation|Comedy|Family|Sport",
    "summary": "It's a big time in Max's life. He's college bound with his friends and finally free of his embarrassing father as he strives to be a top contender for the X-Games. Unfortunately, Goofy loses his job and learns that he cannot get another job without a college degree. To his son's mortification, Goofy decides to join him in his campus to get that degree. Desperate to distract his father, Max talks him into joining the competing Gamma Fraternity team and introduces him to a wonderful librarian who shares his nostalgic love for 1970's pastimes. Unfortunately, things do not go according to plan as events put this father-son relationship to the test.",
    "ImageURL": "https://lumiere-a.akamaihd.net/v1/images/h_anextremelygoofymovie_mobile_19641_fbfc3fc9.jpeg?region=0,0,640,480",
    "imdb_id": "tt0208185",
    "imdb_rating": 6.4,
    "runtime": 79,
    "language": "English",
    "ytid": "H8oSvldAGfg"
},
{
    "Title": "Peter Rabbit",
    "fulltitle": "Peter Rabbit (2018)",
    "movie_year": 2018,
    "Categories": "Adventure|Animation|Comedy|Family|Fantasy",
    "summary": "Based on the books by Beatrix Potter: Peter Rabbit (James Corden;) his three sisters: Flopsy (Margot Robbie,) Mopsy (Elizabeth Debicki) and Cotton Tail (Daisy Ridley) and their cousin Benjamin (Colin Moody) enjoy their days harassing Mr McGregor in his vegetable garden. Until one day he dies and no one can stop them roaming across his house and lands for a full day or so. However, when one of Mr McGregor's relatives inherits the house and goes to check it out, he finds much more than he bargained for. What ensues, is a battle of wills between the new Mr McGregor and the rabbits. But when he starts to fall in love with Bea (Rose Byrne,) a real lover of all nature, his feelings towards them begin to change. But is it too late?",
    "ImageURL": "https://www.storynory.com/wp-content/uploads/2015/01/peterrabbit.jpg",
    "imdb_id": "tt5117670",
    "imdb_rating": 6.6,
    "runtime": 95,
    "language": "English",
    "ytid": "7Pa_Weidt08"
},
{
    "Title": "Love Songs",
    "fulltitle": "Love Songs (2007)",
    "movie_year": 2007,
    "Categories": "Uncategorized",
    "summary": "Julie's boyfriend Ismaël lives with her; rather than worry about the time he spends with his colleague Alice, Julie invites Alice to join them. The three walk the streets of Paris, party, read, and sleep together. Sometimes it's lighthearted, sometimes there are jealousies. Then death strikes. In various ways, those left come to terms with the departure and absence of a loved one: showing concern, eating together, attempting new relationships, trying to \"be there\" for the other. Then, the spirit returns and new commitments are possible. The romantic elements of musical comedy play in contrast to the ambivalence of the lyrics and the story.",
    "ImageURL": "https://www.stlyrics.com/images/ama/movielovesongs_5470.jpg",
    "imdb_id": "tt0996605",
    "imdb_rating": 7.2,
    "runtime": 91,
    "language": "English",
    "ytid": "s54vpKAFmS0"
},
{
    "Title": "The Foster Boy",
    "fulltitle": "The Foster Boy (2011)",
    "movie_year": 2011,
    "Categories": "Drama",
    "summary": "The illegitimate orphan child, 12-year-old Max, is sold by the local minister for a basket of food to the Bösiger family, who own a mountain farm. Max' initial hope of finally finding a loving home is brutally shattered: The farmer and his wife treat Max like livestock, and their son Jacob humiliates and abuses him. Only the local teacher notices the child suffering on the farm.",
    "ImageURL": "https://1.bp.blogspot.com/-tC8IR-ZUneg/YCwoobFftyI/AAAAAAAApE4/Yt0gCFCcUvAWzb2B28TdlnyLwID6c006wCNcBGAsYHQ/s2048/F35B5B8B-4AB8-40BF-B006-6CB2B05099A7.jpeg",
    "imdb_id": "tt2057931",
    "imdb_rating": 7.4,
    "runtime": 107,
    "language": "English",
    "ytid": "E9Qv_XVJ-js"
}
]